import type { LayoutPattern, UiStrategy } from './ui-strategy-types.js';

export const UI_STRATEGIES: Record<LayoutPattern, UiStrategy> = {
  calendar: {
    id: 'calendar-first',
    name: 'Calendar-First Booking',
    description: 'Schedule-centric interface for reservations and appointments',
    bestForDomains: ['booking-system', 'calendar'],
    layoutPattern: 'calendar',
    primarySurface: 'schedule-grid',
    secondarySurfaces: ['today-timeline', 'time-slots', 'upcoming-list'],
    navigationModel: 'date-first',
    interactionModel: 'slot-selection',
    requiredComponents: ['ScheduleGrid', 'TodayTimeline', 'TimeSlotsPanel', 'UpcomingReservations'],
    optionalComponents: ['AvailabilityView', 'StatusChips'],
    dataDisplayPattern: 'timeline-and-slots',
    primaryUserGoal: 'Manage bookings across dates and time slots',
    supportedActions: ['create', 'edit', 'delete', 'filter', 'search'],
  },
  kanban: {
    id: 'kanban-pipeline',
    name: 'Kanban Pipeline',
    description: 'Column-based pipeline for deals and customer stages',
    bestForDomains: ['crm'],
    layoutPattern: 'kanban',
    primarySurface: 'pipeline-board',
    secondarySurfaces: ['follow-up-queue', 'deal-detail-panel'],
    navigationModel: 'stage-columns',
    interactionModel: 'drag-card',
    requiredComponents: ['PipelineBoard', 'PipelineColumn', 'DealCard', 'FollowUpQueue'],
    optionalComponents: ['PipelineSummary', 'CustomerDetailPanel'],
    dataDisplayPattern: 'stage-columns',
    primaryUserGoal: 'Track pipeline stages and customer progress',
    supportedActions: ['create', 'edit', 'delete', 'filter', 'search'],
  },
  'data-table': {
    id: 'stock-table',
    name: 'Stock Data Table',
    description: 'Tabular stock management with reorder highlighting',
    bestForDomains: ['inventory-system'],
    layoutPattern: 'data-table',
    primarySurface: 'product-table',
    secondarySurfaces: ['stock-summary', 'low-stock-alerts'],
    navigationModel: 'table-rows',
    interactionModel: 'row-selection',
    requiredComponents: ['ProductTable', 'StockSummary', 'LowStockAlerts'],
    optionalComponents: ['CategoryFilter', 'StockValuePanel'],
    dataDisplayPattern: 'sortable-table',
    primaryUserGoal: 'Monitor inventory levels and reorder points',
    supportedActions: ['create', 'edit', 'delete', 'filter', 'search', 'sort'],
  },
  'card-grid': {
    id: 'recipe-card-grid',
    name: 'Recipe Card Grid',
    description: 'Visual card browser for recipes and content galleries',
    bestForDomains: ['recipe-manager'],
    layoutPattern: 'card-grid',
    primarySurface: 'recipe-card-grid',
    secondarySurfaces: ['recipe-detail-panel', 'category-filters'],
    navigationModel: 'grid-browse',
    interactionModel: 'card-selection',
    requiredComponents: ['RecipeCardGrid', 'RecipeDetailPanel', 'CategoryFilters'],
    optionalComponents: ['FavoritesRow', 'IngredientsPreview'],
    dataDisplayPattern: 'responsive-card-grid',
    primaryUserGoal: 'Browse and manage recipe collections',
    supportedActions: ['create', 'edit', 'delete', 'filter', 'search'],
  },
  editor: {
    id: 'notes-editor',
    name: 'Editor Workspace',
    description: 'Sidebar plus main editor pane for writing apps',
    bestForDomains: ['notes-app'],
    layoutPattern: 'editor',
    primarySurface: 'editor-pane',
    secondarySurfaces: ['notes-sidebar', 'tags-panel'],
    navigationModel: 'sidebar-list',
    interactionModel: 'editor-focus',
    requiredComponents: ['NotesSidebar', 'EditorPane', 'TagsPanel'],
    optionalComponents: ['PinnedNotes', 'SearchBar'],
    dataDisplayPattern: 'sidebar-editor-split',
    primaryUserGoal: 'Write, organize, and search notes',
    supportedActions: ['create', 'edit', 'delete', 'search', 'filter'],
  },
  ledger: {
    id: 'finance-ledger',
    name: 'Finance Ledger',
    description: 'Balance summary with income/expense transaction ledger',
    bestForDomains: ['expense-tracker', 'budget-planner', 'invoice-system'],
    layoutPattern: 'ledger',
    primarySurface: 'transaction-ledger',
    secondarySurfaces: ['balance-summary', 'category-breakdown'],
    navigationModel: 'ledger-rows',
    interactionModel: 'transaction-entry',
    requiredComponents: ['BalanceSummary', 'TransactionLedger', 'CategoryBreakdown'],
    optionalComponents: ['MonthlyTotals', 'FilterBar'],
    dataDisplayPattern: 'ledger-table',
    primaryUserGoal: 'Track income, expenses, and running balance',
    supportedActions: ['create', 'edit', 'delete', 'filter', 'search'],
  },
  pos: {
    id: 'restaurant-pos',
    name: 'Point of Sale',
    description: 'Menu grid with active order cart for order-taking',
    bestForDomains: ['restaurant-pos'],
    layoutPattern: 'pos',
    primarySurface: 'menu-grid',
    secondarySurfaces: ['order-cart', 'checkout-panel'],
    navigationModel: 'category-tabs',
    interactionModel: 'cart-add',
    requiredComponents: ['MenuGrid', 'OrderCart', 'CheckoutPanel'],
    optionalComponents: ['MenuCategories', 'QuantityControls'],
    dataDisplayPattern: 'menu-plus-cart',
    primaryUserGoal: 'Take orders and manage an active cart',
    supportedActions: ['create', 'edit', 'delete', 'filter'],
  },
  chat: {
    id: 'conversation-chat',
    name: 'Conversation Interface',
    description: 'Conversation list with message thread and composer',
    bestForDomains: ['chat-app', 'messaging-app'],
    layoutPattern: 'chat',
    primarySurface: 'message-thread',
    secondarySurfaces: ['conversation-list', 'message-composer'],
    navigationModel: 'conversation-list',
    interactionModel: 'message-compose',
    requiredComponents: ['ConversationList', 'MessageThread', 'MessageComposer'],
    optionalComponents: ['ContactStatus', 'UnreadIndicators'],
    dataDisplayPattern: 'split-conversation',
    primaryUserGoal: 'Read and send messages in conversations',
    supportedActions: ['create', 'edit', 'delete', 'search'],
  },
  'media-library': {
    id: 'media-library',
    name: 'Media Library',
    description: 'Playlist sidebar with track list and now playing area',
    bestForDomains: ['music-app', 'playlist-app', 'media-library'],
    layoutPattern: 'media-library',
    primarySurface: 'track-list',
    secondarySurfaces: ['playlist-sidebar', 'now-playing'],
    navigationModel: 'playlist-sidebar',
    interactionModel: 'track-selection',
    requiredComponents: ['PlaylistSidebar', 'TrackList', 'NowPlayingPanel'],
    optionalComponents: ['QueuePanel', 'ArtistMetadata'],
    dataDisplayPattern: 'library-split',
    primaryUserGoal: 'Browse playlists and manage a playback queue',
    supportedActions: ['create', 'edit', 'delete', 'search', 'filter'],
  },
  timetable: {
    id: 'school-timetable',
    name: 'Timetable Classroom',
    description: 'Day/week timetable with classes and attendance',
    bestForDomains: ['school-portal'],
    layoutPattern: 'timetable',
    primarySurface: 'timetable-grid',
    secondarySurfaces: ['class-cards', 'upcoming-lessons'],
    navigationModel: 'day-week-tabs',
    interactionModel: 'class-selection',
    requiredComponents: ['TimetableGrid', 'ClassCards', 'UpcomingLessons'],
    optionalComponents: ['AttendanceCards', 'TeacherStudentSections'],
    dataDisplayPattern: 'timetable-grid',
    primaryUserGoal: 'View schedules, classes, and upcoming lessons',
    supportedActions: ['create', 'edit', 'delete', 'filter', 'search'],
  },
  'progress-dashboard': {
    id: 'progress-dashboard',
    name: 'Progress Dashboard',
    description: 'Checklist, streaks, and weekly progress tracking',
    bestForDomains: ['habit-tracker', 'fitness-tracker'],
    layoutPattern: 'progress-dashboard',
    primarySurface: 'today-checklist',
    secondarySurfaces: ['streak-panel', 'weekly-progress', 'goal-cards'],
    navigationModel: 'progress-sections',
    interactionModel: 'checklist-toggle',
    requiredComponents: ['TodayChecklist', 'StreakPanel', 'WeeklyProgress', 'GoalCards'],
    optionalComponents: ['ProgressBars', 'HistorySummary'],
    dataDisplayPattern: 'progress-sections',
    primaryUserGoal: 'Track habits, streaks, and weekly goals',
    supportedActions: ['create', 'edit', 'delete', 'filter', 'search'],
  },
  board: {
    id: 'project-board',
    name: 'Project Board',
    description: 'Kanban board for tasks with priorities and due dates',
    bestForDomains: ['project-manager', 'task-manager'],
    layoutPattern: 'board',
    primarySurface: 'task-board',
    secondarySurfaces: ['priority-summary', 'due-date-panel'],
    navigationModel: 'board-columns',
    interactionModel: 'task-card',
    requiredComponents: ['TaskBoard', 'BoardColumn', 'TaskCard'],
    optionalComponents: ['PrioritySummary', 'DueDatePanel'],
    dataDisplayPattern: 'kanban-board',
    primaryUserGoal: 'Organize tasks across status columns',
    supportedActions: ['create', 'edit', 'delete', 'filter', 'search'],
  },
  dashboard: {
    id: 'domain-dashboard',
    name: 'Domain Dashboard',
    description: 'Metrics dashboard with charts and activity panels',
    bestForDomains: ['generic-application'],
    layoutPattern: 'dashboard',
    primarySurface: 'metrics-dashboard',
    secondarySurfaces: ['chart-panel', 'recent-activity'],
    navigationModel: 'dashboard-sections',
    interactionModel: 'dashboard-overview',
    requiredComponents: ['DashboardSummary', 'ChartPlaceholder', 'RecentActivityPanel'],
    optionalComponents: ['FilterBar', 'SearchBar'],
    dataDisplayPattern: 'dashboard-panels',
    primaryUserGoal: 'Overview metrics and recent activity',
    supportedActions: ['create', 'edit', 'delete', 'filter', 'search'],
  },
  'split-view': {
    id: 'split-view-crud',
    name: 'Split View CRUD',
    description: 'List and detail split view with search and filters',
    bestForDomains: ['generic-application', 'contact-manager', 'countdown-timer'],
    layoutPattern: 'split-view',
    primarySurface: 'list-detail-split',
    secondarySurfaces: ['search-filter-bar', 'detail-panel'],
    navigationModel: 'list-detail',
    interactionModel: 'list-selection',
    requiredComponents: ['EntityListView', 'EntityCardView', 'FilterBar'],
    optionalComponents: ['DashboardSummary', 'SearchBar'],
    dataDisplayPattern: 'list-detail-split',
    primaryUserGoal: 'Browse records and manage details',
    supportedActions: ['create', 'edit', 'delete', 'filter', 'search', 'sort'],
  },
};

export const DEFAULT_LAYOUT_PATTERN: LayoutPattern = 'split-view';

export function getUiStrategyByPattern(pattern: LayoutPattern): UiStrategy {
  return UI_STRATEGIES[pattern];
}

export function getUiStrategyById(id: string): UiStrategy | undefined {
  return Object.values(UI_STRATEGIES).find((strategy) => strategy.id === id);
}
